from typing import Any, Protocol, List, Dict


class ScriptInterface(Protocol):
    def get_enrolado(self, limite: int) -> Any: ...

    def get_enrolado_by_ruc(self, ruc: str) -> Any: ...

    def save_enrolado(self, datos: dict) -> None: ...


class APIClientInterface(Protocol):
    def get_token(self, ruc: str, usuario_sol: str, clave_sol: str, id: str, clave: str) -> str: ...

    def _get_headers(self, token_acceso: str) -> dict: ...

    def solicitar_descarga(self, periodo: str, token_acceso: str) -> str: ...

    def verificar_estado(self, numero_ticket: str, token_acceso: str, periodo: str) -> dict: ...

    def descargar_archivo(
        self, datos_archivo: dict, token_acceso: str, periodo: str, numero_ticket: str
    ) -> str: ...
