from typing import Any, Protocol


class ScriptInterface(Protocol):
    def get_enrolado(self) -> Any: ...

class APIClientInterface(Protocol):
    def get_token(self, ruc, usuario_sol, clave_sol, id, clave) -> str: ...

    def _get_headers(self, token_acceso) -> dict: ...

    def solicitar_descarga(self, periodo, token_acceso) -> str: ...

    def verificar_estado(self, numero_ticket, token_acceso, periodo) -> dict: ...

    def descargar_archivo(
        self, datos_archivo, token_acceso, periodo, numero_ticket
    ) -> None: ...
